In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
dataset.shape

(399, 28)

In [6]:
dataset.value_counts()

age   bp         al   su   bgr         bu          sc        sod         pot       hrmo       pcv        wc           rc        sg_b  sg_c  sg_d  sg_e  rbc_normal  pc_normal  pcc_present  ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes
2.0   76.459948  3.0  0.0  148.112676  57.482105   3.077356  137.528754  4.627244  12.518156  38.868902  8408.191126  4.705597  0     1     0     0     1           0          0            0           0        0       0        1          1       0        1                     1
61.0  90.000000  0.0  2.0  148.112676  57.482105   3.077356  137.528754  4.627244  12.518156  38.868902  9800.000000  4.705597  0     0     1     0     1           1          0            0           0        1       0        0          0       1        1                     1
      80.000000  0.0  4.0  360.000000  19.000000   0.700000  137.000000  4.400000  15.200000  44.000000  8300.000000  5.200000  0     0     1     0     1           1          0            0           1        1       0        1          0       0        1                     1
                      0.0  131.000000  23.000000   0.800000  140.000000  4.100000  11.300000  35.000000  8408.191126  4.705597  0     0     0     0     1           1          0            0           0        0       0        1          0       0        1                     1
      70.000000  0.0  0.0  133.000000  38.000000   1.000000  142.000000  3.600000  13.700000  47.000000  9200.000000  4.900000  1     0     0     0     1           1          0            0           0        0       0        1          0       0        0                     1
                                                                                                                                                                                                                                                                                   ..
46.0  90.000000  0.0  0.0  213.000000  68.000000   2.800000  146.000000  6.300000  9.300000   38.868902  8408.191126  4.705597  0     0     0     0     1           1          0            0           1        1       0        1          0       0        1                     1
      80.000000  0.0  0.0  160.000000  40.000000   2.000000  140.000000  4.100000  9.000000   27.000000  8100.000000  3.200000  0     1     0     0     1           1          0            0           1        0       0        0          0       1        1                     1
      70.000000  1.0  0.0  150.000000  111.000000  6.100000  131.000000  3.700000  7.500000   27.000000  8408.191126  4.705597  0     0     1     0     0           1          0            0           0        0       0        1          0       1        1                     1
                 0.0  0.0  100.000000  47.000000   0.500000  142.000000  3.500000  16.400000  43.000000  5700.000000  6.500000  1     0     0     0     1           1          0            0           0        0       0        1          0       0        0                     1
90.0  90.000000  1.0  0.0  139.000000  89.000000   3.000000  140.000000  4.100000  12.000000  37.000000  7900.000000  3.900000  1     0     0     0     1           1          0            0           1        1       0        1          0       0        1                     1
Length: 399, dtype: int64

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [8]:
dependent=dataset[['classification_yes']]
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [9]:
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [11]:
# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()
# x_train=sc.fit_transform(x_train)
# y_train=sc.fit(y_train)

In [36]:
from sklearn.cluster import KMeans
classifier=KMeans()
classifier.fit(x_train,y_train)
from sklearn.model_selection import GridSearchCV
grid_params={'algorithm':['lloyd', 'elkan', 'auto', 'full']}
grid=GridSearchCV(classifier,grid_params,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)
# algorithm{“lloyd”, “elkan”, “auto”, “full”}

C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

Fitting 5 folds for each of 4 candidates, totalling 20 fits

C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

GridSearchCV(estimator=KMeans(), n_jobs=-1,
             param_grid={'algorithm': ['lloyd', 'elkan', 'auto', 'full']},
             scoring='f1_weighted', verbose=3)

In [37]:
result=grid.cv_results_
result

{'mean_fit_time': array([1.89522958, 0.25264254, 1.85345478, 1.94259992]),
 'std_fit_time': array([0.8086396 , 0.05831968, 0.55620267, 0.32571945]),
 'mean_score_time': array([0.13551593, 0.19088283, 0.16150007, 0.16209922]),
 'std_score_time': array([0.02504849, 0.06736776, 0.07556208, 0.05955284]),
 'param_algorithm': masked_array(data=['lloyd', 'elkan', 'auto', 'full'],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'algorithm': 'lloyd'},
  {'algorithm': 'elkan'},
  {'algorithm': 'auto'},
  {'algorithm': 'full'}],
 'split0_test_score': array([0.27619048, 0.51681174, 0.3758948 , 0.26318027]),
 'split1_test_score': array([0.34663866, 0.27401478, 0.31999362, 0.31999362]),
 'split2_test_score': array([0.20017483, 0.25458211, 0.16845165, 0.08522727]),
 'split3_test_score': array([0.19690476, 0.2202765 , 0.21547619, 0.19961735]),
 'split4_test_score': array([0.12418972, 0.1246629 , 0.24390244, 0.1246629 ]),
 'mean_test_score': array([0.22881969, 0.27806961, 0.26474374, 0.19853628]),
 'std_test_score': array([0.07604186, 0.12995351, 0.07421715, 0.08628802]),
 'rank_test_score': array([3, 1, 2, 4])}

In [38]:
grid_pred=grid.predict(x_test)
grid_pred

array([7, 0, 5, 1, 5, 0, 5, 0, 0, 5, 3, 0, 3, 0, 3, 5, 0, 3, 7, 3, 2, 7,
       0, 5, 2, 5, 7, 7, 0, 6, 0, 0, 0, 0, 0, 7, 0, 5, 1, 0, 3, 1, 7, 1,
       0, 3, 0, 5, 0, 4, 6, 3, 1, 0, 1, 3, 3, 0, 5, 5, 7, 5, 1, 0, 0, 5,
       3, 6, 7, 5, 3, 5, 3, 0, 3, 3, 3, 5, 4, 3, 0, 0, 3, 3, 3, 0, 0, 0,
       5, 5, 0, 0, 7, 0, 7, 7, 0, 0, 0, 0, 0, 0, 7, 7, 0, 0, 0, 0, 5, 0,
       0, 5, 3, 2, 0, 2, 0, 5, 3, 2])

In [39]:
solution=grid.best_params_
solution

{'algorithm': 'elkan'}

In [40]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, grid_pred)
print(cm)

[[11  0  3 11  0 12  0  8]
 [35  7  2 11  2  9  3  6]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]

In [41]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test, grid_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.24      0.24      0.24        45
           1       1.00      0.09      0.17        75
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0

    accuracy                           0.15       120
   macro avg       0.15      0.04      0.05       120
weighted avg       0.71      0.15      0.20       120

C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [42]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.895230,0.808640,0.135516,0.025048,lloyd,{'algorithm': 'lloyd'},0.276190,0.346639,0.200175,0.196905,0.124190,0.228820,0.076042,3
1,0.252643,0.058320,0.190883,0.067368,elkan,{'algorithm': 'elkan'},0.516812,0.274015,0.254582,0.220276,0.124663,0.278070,0.129954,1
2,1.853455,0.556203,0.161500,0.075562,auto,{'algorithm': 'auto'},0.375895,0.319994,0.168452,0.215476,0.243902,0.264744,0.074217,2
3,1.942600,0.325719,0.162099,0.059553,full,{'algorithm': 'full'},0.263180,0.319994,0.085227,0.199617,0.124663,0.198536,0.086288,4

In [43]:
print("the result is:{}".format(grid.best_params_))

the result is:{'algorithm': 'elkan'}

In [44]:
from sklearn.metrics import roc_auc_score
roc_score=roc_auc_score(y_test, grid.predict_proba(x_test)[:,1])
roc_score

AttributeError: 'KMeans' object has no attribute 'predict_proba'

In [45]:
# import pickle as pkl
# file_name="multinominal_nb_final.sav"

In [ ]:
# pkl.dump(classifier,open(file_name, "wb"))

In [ ]:
# # # 'age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
# #        'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
# #        'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
# #        'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'

# load_file=pkl.load(open(file_name, "rb"))
# age=int(input("Enter your Age: "))
# bp=int(input("Enter your Blood pressure: "))
# al=int(input("Enter your AL value: "))
# su=int(input("Enter your SU value: "))
# bgr=int(input("Enter your BGR value: "))
# bu=int(input("Enter your BU value: "))
# sc=int(input("Enter your SC value: "))
# sod=int(input("Enter your SOD value: "))
# pot=int(input("Enter your POT value: "))
# hrmo=int(input("Enter your HRMO value: "))
# pcv=int(input("Enter your PCV value: "))
# wc=int(input("Enter your WC value: "))
# rc=int(input("Enter your RC value: "))
# sg_b=int(input("Enter your SG_B value: "))
# sg_c=int(input("Enter your SG_C value: "))
# sg_d=int(input("Enter your SG_D value: "))
# sg_e=int(input("Enter your SG_E value: "))
# rbc=int(input("Enter your RBC value(Normal=1/abnormal=0): "))
# pc=int(input("Enter your PC value(Normal=1/abnormal=0): "))
# pcc=int(input("Enter your PCC value(Present=1/Absent=0): "))
# ba=int(input("Enter your BA value(Present=1/Absent=0): "))
# htn=int(input("Enter your HTN value(Yes=1/No=0): "))
# dm=int(input("Enter your DM value(Yes=1/No=0): "))
# cad=int(input("Enter your CAD value(Yes=1/No=0)): "))
# appet=int(input("Enter your APPET value(Yes=1/No=0): "))
# pe=int(input("Enter your PE value(Yes=1/No=0): "))
# ana=int(input("Enter your ANA value(Yes=1/No=0): "))

# answer=load_file.predict([[age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,sg_b,sg_c,sg_d,sg_e,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ana]])
# print("The Chronic Kidney Disease (Yes=1/No=0): {}".format(answer))